name: Parental Escape
favicon: null
layout_spectrum: 0.6719660216476768
typography_spectrum: 0.3896899751853198
title: Parental Escape
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-79275521-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
